spring:
  rabbitmq:
    host: 192.168.5.150
    port: 5672
    username: user
    password: bitnami
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 1
          max-interval: 10s
          multiplier: 2
server:
  port: 0
tmdb:
  apikey: 1012d785312735b8039a9f7f172354cb
  language: es-ES
