spring:
    rabbitmq:
        host: rabbitmq
        listener:
            simple:
                retry:
                    enabled: true
                    initial-interval: 3s
                    max-attempts: 1
                    max-interval: 10s
                    multiplier: 2

tmdb:
    apikey: 1012d785312735b8039a9f7f172354cb
    language: es-ES
