name: TMDB CI - MAIN 
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  test-nightly:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build Maven
        run: mvn test -s .mvn/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      - name: Send telegram message
        if: always()
        uses: xinthink/action-telegram@v1
        with:
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_TO }}
          jobStatus: ${{ job.status }}
          skipSuccess: true
  generate-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      version-released: ${{steps.mvn-release.outputs.version-released}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - uses: luiscajl/mvn-release@main
        id: mvn-release
  build-and-push-to-registry-on-main:
    runs-on: ubuntu-latest
    needs: generate-release
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: luiscajl/mvn-build-push-dockerhub@main
        with:
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}
          github_workspace: $GITHUB_WORKSPACE
          github_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}      
  next-version-for-develop:
    runs-on: ubuntu-latest
    needs: build-and-push-to-registry-on-main
    if: (github.ref == 'refs/heads/main')  && (github.event_name == 'push')
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
        with:
          ref: develop   
      - uses: luiscajl/next-maven-snapshot@main
  notification:
    needs: [next-version-for-develop]
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New version deployed on dockerhub: `docker pull lavandadelpatio/tmdb:${{jobs.generate-release.outputs.version-released}}`