name: TMDB CI - DEVELOP 
on:
  push:
    branches:
      - "develop"
  workflow_dispatch:
jobs:
  build-and-push-to-registry-on-develop:
    runs-on: ubuntu-latest
    if: ( github.event_name == 'push')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: luiscajl/mvn-build-push-dockerhub@main
        with:
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}
          github_workspace: $GITHUB_WORKSPACE
          github_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
  pull-request:
    runs-on: ubuntu-latest
    needs: build-and-push-to-registry-on-develop
    if: (github.event_name == 'push')  && ( github.event.pusher.email == 'luisca_jl@hotmail.com')
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        id: open-pr
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        if: ${{steps.open-pr.outputs.pr_url}}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New pull-request: 

            Repository: ${{ github.repository }}

            See on: ${{steps.open-pr.outputs.pr_url}}